# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:title
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WebCulum -  Know the WEB
email: webculum@gmail.com
author: The WebCulum team
name: Gene Kastyshyn
description: > # this means to ignore newlines until "baseurl:"
  Webculum is designed to be the best way to learn Web related technologies. For learners and teachers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://webculum.org" # the base hostname & protocol for your site
twitter_username: webculm
github_username:  docentmail


# Build settings
markdown: kramdown
